# Generated by Django 6.0.2 on 2026-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('genre_trends', 'Genre Trends'), ('streaming_insights', 'Streaming Insights'), ('touring_data', 'Touring Data'), ('sync_opportunities', 'Sync Opportunities')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(help_text='Dynamic data like chart positions, venue availability')),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this data becomes stale')),
            ],
        ),
        migrations.CreateModel(
            name='UserMetricsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=50)),
                ('data_file', models.FileField(help_text='CSV/JSON data file', upload_to='metrics_uploads/')),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('monthly_listeners', models.IntegerField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
