# Generated by Django 6.0.3 on 2026-05-09 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('sub_genre', models.CharField(blank=True, max_length=100)),
                ('bpm', models.IntegerField()),
                ('key', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('moods', models.JSONField(default=list)),
                ('tags', models.TextField(blank=True)),
                ('audio_file_url', models.URLField(blank=True)),
                ('cover_art_url', models.URLField(blank=True)),
                ('streaming_links', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
