# Generated by Django 6.0.2 on 2026-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', help_text='pending, processing, completed, failed', max_length=20)),
                ('career_score', models.FloatField(default=0.0, help_text='A score from 0-100')),
                ('trajectory_forecast', models.JSONField(default=dict, help_text="e.g., {'next_12_months': 'upward', 'risk_factors': [...]}")),
                ('actionable_insights', models.JSONField(default=list, help_text='List of insights generated by the ML model')),
                ('peer_cluster', models.CharField(blank=True, help_text='Identifier for comparable artists', max_length=100)),
                ('raw_ml_output', models.JSONField(blank=True, help_text='Full ML output for debugging', null=True)),
                ('last_analysis_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_horizon', models.CharField(choices=[('12 months', '12 months'), ('24 months', '24 months'), ('36 months', '36 months')], default='24 months', max_length=20)),
                ('total_revenue_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('priority_actions', models.JSONField(default=list, help_text='A list of key focus areas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Sequence order')),
            ],
            options={
                'ordering': ['order', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musical_skill_score', models.IntegerField(default=0)),
                ('technical_skill_score', models.IntegerField(default=0)),
                ('business_skill_score', models.IntegerField(default=0)),
                ('skill_gaps', models.JSONField(default=list, help_text="e.g., ['Mixing Mastery', 'Music Publishing Law']")),
                ('recommended_training', models.JSONField(default=list, help_text="e.g., ['Link to course A', 'Link to tutorial B']")),
                ('benchmark_data', models.JSONField(default=dict, help_text='Comparative data')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
