# Generated by Django 6.0.2 on 2026-03-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranalysis',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_analysis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='ai_engine.careerroadmap'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessment', to=settings.AUTH_USER_MODEL),
        ),
    ]
