from django.db import models
from django.conf import settings

class CareerAnalysis(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='career_analysis')
    status = models.CharField(max_length=20, default='pending', help_text="pending, processing, completed, failed")
    career_score = models.FloatField(default=0.0, help_text="A score from 0-100")
    trajectory_forecast = models.JSONField(default=dict, help_text="e.g., {'next_12_months': 'upward', 'risk_factors': [...]}")
    actionable_insights = models.JSONField(default=list, help_text="List of insights generated by the ML model")
    peer_cluster = models.CharField(max_length=100, blank=True, help_text="Identifier for comparable artists")
    raw_ml_output = models.JSONField(null=True, blank=True, help_text="Full ML output for debugging")
    last_analysis_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Analysis for {self.user.username}"

class SkillAssessment(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='skill_assessment')
    musical_skill_score = models.IntegerField(default=0)
    technical_skill_score = models.IntegerField(default=0)
    business_skill_score = models.IntegerField(default=0)
    skill_gaps = models.JSONField(default=list, help_text="e.g., ['Mixing Mastery', 'Music Publishing Law']")
    recommended_training = models.JSONField(default=list, help_text="e.g., ['Link to course A', 'Link to tutorial B']")
    benchmark_data = models.JSONField(default=dict, help_text="Comparative data")
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Skills for {self.user.username}"

class CareerRoadmap(models.Model):
    HORIZON_CHOICES = [
        ('12 months', '12 months'),
        ('24 months', '24 months'),
        ('36 months', '36 months'),
    ]
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='roadmap')
    time_horizon = models.CharField(max_length=20, choices=HORIZON_CHOICES, default='24 months')
    total_revenue_target = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    priority_actions = models.JSONField(default=list, help_text="A list of key focus areas")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Roadmap for {self.user.username}"

class Milestone(models.Model):
    roadmap = models.ForeignKey(CareerRoadmap, on_delete=models.CASCADE, related_name='milestones')
    title = models.CharField(max_length=255)
    description = models.TextField()
    target_date = models.DateField()
    is_completed = models.BooleanField(default=False)
    order = models.IntegerField(default=0, help_text="Sequence order")

    class Meta:
        ordering = ['order', 'target_date']

    def __str__(self):
        return f"{self.roadmap.user.username}: {self.title}"
