# Generated by Django 6.0.2 on 2026-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_entity', models.CharField(blank=True, help_text="e.g. 'Atlantic Records'", max_length=255, null=True)),
                ('match_type', models.CharField(choices=[('collaborator', 'Collaborator'), ('label', 'Label'), ('publisher', 'Publisher'), ('sync_supervisor', 'Sync Supervisor')], max_length=50)),
                ('compatibility_score', models.FloatField(help_text='Score from compatibility algorithm')),
                ('reasoning', models.TextField(help_text='AI generated explanation of the match')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
