# Generated by Django 6.0.2 on 2026-03-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationmatch',
            name='matched_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_to_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationmatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
